component_depth: 1
languages:
- java
exclude:
- ./ant/.*
- ./bin/.*
- ./bin/org/.*
- ./bin/org/jfree/.*
- ./bin/org/jfree/chart/.*
- ./bin/org/jfree/chart/annotations/.*
- ./bin/org/jfree/chart/annotations/junit/.*
- ./bin/org/jfree/chart/axis/.*
- ./bin/org/jfree/chart/axis/junit/.*
- ./bin/org/jfree/chart/block/.*
- ./bin/org/jfree/chart/block/junit/.*
- ./bin/org/jfree/chart/demo/.*
- ./bin/org/jfree/chart/editor/.*
- ./bin/org/jfree/chart/encoders/.*
- ./bin/org/jfree/chart/entity/.*
- ./bin/org/jfree/chart/entity/junit/.*
- ./bin/org/jfree/chart/event/.*
- ./bin/org/jfree/chart/imagemap/.*
- ./bin/org/jfree/chart/imagemap/junit/.*
- ./bin/org/jfree/chart/junit/.*
- ./bin/org/jfree/chart/labels/.*
- ./bin/org/jfree/chart/labels/junit/.*
- ./bin/org/jfree/chart/needle/.*
- ./bin/org/jfree/chart/needle/junit/.*
- ./bin/org/jfree/chart/panel/.*
- ./bin/org/jfree/chart/panel/junit/.*
- ./bin/org/jfree/chart/plot/.*
- ./bin/org/jfree/chart/plot/dial/.*
- ./bin/org/jfree/chart/plot/dial/junit/.*
- ./bin/org/jfree/chart/plot/junit/.*
- ./bin/org/jfree/chart/renderer/.*
- ./bin/org/jfree/chart/renderer/category/.*
- ./bin/org/jfree/chart/renderer/category/junit/.*
- ./bin/org/jfree/chart/renderer/junit/.*
- ./bin/org/jfree/chart/renderer/xy/.*
- ./bin/org/jfree/chart/renderer/xy/junit/.*
- ./bin/org/jfree/chart/servlet/.*
- ./bin/org/jfree/chart/title/.*
- ./bin/org/jfree/chart/title/junit/.*
- ./bin/org/jfree/chart/urls/.*
- ./bin/org/jfree/chart/urls/junit/.*
- ./bin/org/jfree/chart/util/.*
- ./bin/org/jfree/chart/util/junit/.*
- ./bin/org/jfree/data/.*
- ./bin/org/jfree/data/category/.*
- ./bin/org/jfree/data/category/junit/.*
- ./bin/org/jfree/data/contour/.*
- ./bin/org/jfree/data/function/.*
- ./bin/org/jfree/data/gantt/.*
- ./bin/org/jfree/data/gantt/junit/.*
- ./bin/org/jfree/data/general/.*
- ./bin/org/jfree/data/general/junit/.*
- ./bin/org/jfree/data/io/.*
- ./bin/org/jfree/data/jdbc/.*
- ./bin/org/jfree/data/junit/.*
- ./bin/org/jfree/data/statistics/.*
- ./bin/org/jfree/data/statistics/junit/.*
- ./bin/org/jfree/data/time/.*
- ./bin/org/jfree/data/time/junit/.*
- ./bin/org/jfree/data/time/ohlc/.*
- ./bin/org/jfree/data/time/ohlc/junit/.*
- ./bin/org/jfree/data/xml/.*
- ./bin/org/jfree/data/xy/.*
- ./bin/org/jfree/data/xy/junit/.*
- ./bin/org/jfree/experimental/.*
- ./bin/org/jfree/experimental/chart/.*
- ./bin/org/jfree/experimental/chart/demo/.*
- ./bin/org/jfree/experimental/chart/plot/.*
- ./bin/org/jfree/experimental/chart/renderer/.*
- ./bin/org/jfree/experimental/chart/renderer/xy/.*
- ./bin/org/jfree/experimental/chart/swt/.*
- ./bin/org/jfree/experimental/chart/swt/demo/.*
- ./bin/org/jfree/experimental/chart/swt/editor/.*
- ./bin/org/jfree/experimental/swt/.*
- ./checkstyle/.*
- ./docfiles/.*
- ./experimental/.*
- ./experimental/org/.*
- ./experimental/org/jfree/.*
- ./experimental/org/jfree/experimental/.*
- ./experimental/org/jfree/experimental/chart/.*
- ./experimental/org/jfree/experimental/chart/demo/.*
- ./experimental/org/jfree/experimental/chart/plot/.*
- ./experimental/org/jfree/experimental/chart/renderer/.*
- ./experimental/org/jfree/experimental/chart/renderer/xy/.*
- ./lib/.*
- ./swt/.*
- ./swt/org/.*
- ./swt/org/jfree/.*
- ./swt/org/jfree/experimental/.*
- ./swt/org/jfree/experimental/chart/.*
- ./swt/org/jfree/experimental/chart/swt/.*
- ./swt/org/jfree/experimental/chart/swt/demo/.*
- ./swt/org/jfree/experimental/chart/swt/editor/.*
- ./swt/org/jfree/experimental/swt/.*
- ./tests/.*
- ./tests/org/.*
- ./tests/org/jfree/.*
- ./tests/org/jfree/chart/.*
- ./tests/org/jfree/chart/annotations/.*
- ./tests/org/jfree/chart/annotations/junit/.*
- ./tests/org/jfree/chart/axis/.*
- ./tests/org/jfree/chart/axis/junit/.*
- ./tests/org/jfree/chart/block/.*
- ./tests/org/jfree/chart/block/junit/.*
- ./tests/org/jfree/chart/entity/.*
- ./tests/org/jfree/chart/entity/junit/.*
- ./tests/org/jfree/chart/imagemap/.*
- ./tests/org/jfree/chart/imagemap/junit/.*
- ./tests/org/jfree/chart/junit/.*
- ./tests/org/jfree/chart/labels/.*
- ./tests/org/jfree/chart/labels/junit/.*
- ./tests/org/jfree/chart/needle/.*
- ./tests/org/jfree/chart/needle/junit/.*
- ./tests/org/jfree/chart/panel/.*
- ./tests/org/jfree/chart/panel/junit/.*
- ./tests/org/jfree/chart/plot/.*
- ./tests/org/jfree/chart/plot/dial/.*
- ./tests/org/jfree/chart/plot/dial/junit/.*
- ./tests/org/jfree/chart/plot/junit/.*
- ./tests/org/jfree/chart/renderer/.*
- ./tests/org/jfree/chart/renderer/category/.*
- ./tests/org/jfree/chart/renderer/category/junit/.*
- ./tests/org/jfree/chart/renderer/junit/.*
- ./tests/org/jfree/chart/renderer/xy/.*
- ./tests/org/jfree/chart/renderer/xy/junit/.*
- ./tests/org/jfree/chart/title/.*
- ./tests/org/jfree/chart/title/junit/.*
- ./tests/org/jfree/chart/urls/.*
- ./tests/org/jfree/chart/urls/junit/.*
- ./tests/org/jfree/chart/util/.*
- ./tests/org/jfree/chart/util/junit/.*
- ./tests/org/jfree/data/.*
- ./tests/org/jfree/data/category/.*
- ./tests/org/jfree/data/category/junit/.*
- ./tests/org/jfree/data/gantt/.*
- ./tests/org/jfree/data/gantt/junit/.*
- ./tests/org/jfree/data/general/.*
- ./tests/org/jfree/data/general/junit/.*
- ./tests/org/jfree/data/junit/.*
- ./tests/org/jfree/data/statistics/.*
- ./tests/org/jfree/data/statistics/junit/.*
- ./tests/org/jfree/data/time/.*
- ./tests/org/jfree/data/time/junit/.*
- ./tests/org/jfree/data/time/ohlc/.*
- ./tests/org/jfree/data/time/ohlc/junit/.*
- ./tests/org/jfree/data/xy/.*
- ./tests/org/jfree/data/xy/junit/.*
